from residual import DEATH_COLUMN, FOLLOW_UP_TIME_COLUMN


COLUMNS_TO_DROP_FOR_SCALE = [
    DEATH_COLUMN,
    FOLLOW_UP_TIME_COLUMN
]
COLUMNS_TO_ADD_AFTER_SCALE = [DEATH_COLUMN, FOLLOW_UP_TIME_COLUMN]